# Generated by Django 5.2.4 on 2025-08-04 13:19

import api.models.agent
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IastAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=255)),
                ("version", models.CharField(blank=True, max_length=255)),
                ("latest_time", models.IntegerField()),
                ("is_audit", models.IntegerField()),
                ("is_running", models.IntegerField()),
                ("is_core_running", models.IntegerField()),
                ("control", models.IntegerField()),
                ("is_control", models.IntegerField()),
                ("project_name", models.CharField(blank=True, max_length=255)),
                ("online", models.PositiveSmallIntegerField(default=0)),
                ("language", models.CharField(blank=True, max_length=10)),
                ("filepathsimhash", models.CharField(blank=True, max_length=255)),
                ("servicetype", models.CharField(blank=True, max_length=255)),
                ("alias", models.CharField(blank=True, max_length=255)),
                ("startup_time", models.IntegerField(default=0)),
                ("register_time", models.IntegerField(default=0)),
                ("actual_running_status", models.IntegerField(default=1)),
                ("except_running_status", models.IntegerField(default=1)),
                ("state_status", models.IntegerField(default=1)),
                ("events", models.JSONField(default=api.models.agent.get_events)),
                ("allow_report", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "iast_agent",
            },
        ),
        migrations.CreateModel(
            name="IastServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(blank=True, max_length=255)),
                ("ip", models.CharField(blank=True, max_length=255)),
                ("port", models.IntegerField()),
                ("environment", models.TextField(blank=True, null=True)),
                ("path", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(blank=True, max_length=255)),
                ("container", models.CharField(blank=True, max_length=255)),
                ("container_path", models.CharField(blank=True, max_length=255)),
                ("cluster_name", models.CharField(blank=True, max_length=255)),
                ("cluster_version", models.CharField(blank=True, max_length=100)),
                ("command", models.TextField(blank=True)),
                ("env", models.CharField(blank=True, max_length=255)),
                ("runtime", models.CharField(blank=True, max_length=255)),
                ("create_time", models.IntegerField()),
                ("update_time", models.IntegerField()),
                ("network", models.CharField(blank=True, max_length=255)),
                ("protocol", models.CharField(blank=True, max_length=255)),
                ("pid", models.IntegerField(blank=True)),
                ("ipaddresslist", models.JSONField(default=list)),
            ],
            options={
                "db_table": "iast_server",
            },
        ),
        migrations.CreateModel(
            name="IastAgentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "time",
                    models.IntegerField(blank=True, default=1754313583, null=True),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_events",
                        to="api.iastagent",
                    ),
                ),
            ],
            options={
                "db_table": "iast_agent_event",
            },
        ),
        migrations.AddField(
            model_name="iastagent",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="agents",
                related_query_name="agent",
                to="api.iastserver",
                verbose_name="server",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferences", models.JSONField(blank=True, default=dict)),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("avatar", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api_user_profile",
            },
        ),
    ]
