# Generated by Django 5.2.4 on 2025-08-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iastagentevent',
            name='time',
            field=models.IntegerField(blank=True, default=1754374717, null=True),
        ),
    ]
