---
- name: Install Redis
  apt:
    name: redis-server
    state: present
    update_cache: yes

- name: Configure Redis
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: "^{{ item.regex }}"
    line: "{{ item.line }}"
  loop:
    - { regex: "^bind", line: "bind {{ redis_bind }}" }
    - { regex: "^protected-mode", line: "protected-mode no" }
  notify: Restart Redis

- name: Ensure Redis is running
  service:
    name: redis-server
    state: started
    enabled: yes