permissions:
  contents: read
name: Build & Push Docker Image

on:
  workflow_dispatch:
#  push:
#    branches: [ master ]

jobs:
  read_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'
      - uses: actions/checkout@v4
      - name: Read version
        id: set_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

  build_and_push:
    needs: [read_version]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          stage: server
          tags: |
            l1ghth4t/immunity:${{ needs.read_version.outputs.version }}
            l1ghth4t/immunity:latest
          push: true

  build_and_push_worker:
    needs: [read_version]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          stage: worker
          tags: |
            l1ghth4t/immunity-worker:${{ needs.read_version.outputs.version }}
            l1ghth4t/immunity-worker:latest
          push: true
